[project]
name = "mcp-materialize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.1.18",
    "mcp>=1.5.0",
]
